//      if (patternCount == 0)  {currentStep =           ;           }
// else if (patternCount == 1)  {currentStep =           ;           }
// else if (patternCount == 2)  {currentStep =           ;           }
// else if (patternCount == 3)  {currentStep =           ;           }
// else if (patternCount == 4)  {currentStep =           ;           }
// else if (patternCount == 5)  {currentStep =           ;           }
// else if (patternCount == 6)  {currentStep =           ;           }
// else if (patternCount == 7)  {currentStep =           ;           }
// else if (patternCount == 8)  {currentStep =           ;           }
// else if (patternCount == 9)  {currentStep =           ;           }
// else if (patternCount == 10) {currentStep =           ;           }
// else if (patternCount == 11) {currentStep =           ;           }
// else if (patternCount == 12) {currentStep =           ;           }
// else if (patternCount == 13) {currentStep =           ;           }
// else if (patternCount == 14) {currentStep =           ;           }
// else if (patternCount == 15) {currentStep =           ;           }
// else if (patternCount == 16) {currentStep =           ;           }
// else if (patternCount == 17) {currentStep =           ;           }
// else if (patternCount == 18) {currentStep =           ;           }
// else if (patternCount == 19) {currentStep =           ;           }
// else if (patternCount == 20) {currentStep =           ;           }
// else if (patternCount == 21) {currentStep =           ;           }
// else if (patternCount == 22) {currentStep =           ;           }
// else if (patternCount == 23) {currentStep =           ;           }
// else if (patternCount == 24) {currentStep =           ;           }
// else if (patternCount == 25) {currentStep =           ;           }
// else if (patternCount == 26) {currentStep =           ;           }
// else if (patternCount == 27) {currentStep =           ;           }
// else if (patternCount == 28) {currentStep =           ;           }
// else if (patternCount == 29) {currentStep =           ;           }
// else if (patternCount == 30) {currentStep =           ;           }
// else if (patternCount == 31) {currentStep =           ;           }
// else if (patternCount == 32) {currentStep =           ;           }
// else if (patternCount == 33) {currentStep =           ;           }
// else if (patternCount == 34) {currentStep =           ;           }
// else if (patternCount == 35) {currentStep =           ;           }
// else if (patternCount == 36) {currentStep =           ;           }
// else if (patternCount == 37) {currentStep =           ;           }
// else if (patternCount == 38) {currentStep =           ;           }
// else if (patternCount == 39) {currentStep =           ;           }
// else if (patternCount == 40) {currentStep =           ;           }
// else if (patternCount == 41) {currentStep =           ;           }
// else if (patternCount == 42) {currentStep =           ;           }
// else if (patternCount == 43) {currentStep =           ;           }
// else if (patternCount == 44) {currentStep =           ;           }
// else if (patternCount == 45) {currentStep =           ;           }
// else if (patternCount == 46) {currentStep =           ;           }
// else if (patternCount == 47) {currentStep =           ;           }
// else if (patternCount == 48) {currentStep =           ;           }
// else if (patternCount == 49) {currentStep =           ;           }
// else if (patternCount == 50) {currentStep =           ;           }
// else if (patternCount == 51) {currentStep =           ;           }
// else if (patternCount == 52) {currentStep =           ;           }
// else if (patternCount == 53) {currentStep =           ;           }
// else if (patternCount == 54) {currentStep =           ;           }
// else if (patternCount == 55) {currentStep =           ;           }
// else if (patternCount == 56) {currentStep =           ;           }
// else if (patternCount == 57) {currentStep =           ;           }
// else if (patternCount == 58) {currentStep =           ;           }
// else if (patternCount == 59) {currentStep =           ;           }
// else if (patternCount == 60) {currentStep =           ;           }
// else if (patternCount == 61) {currentStep =           ;           }
// else if (patternCount == 62) {currentStep =           ;           }
// else if (patternCount == 63) {currentStep =           ;           }